export const collectionTaglines: Record<string, string> = {
  "bmw-1-series": "Four generations of the compact BMW.",
  "bmw-3-series": "The changing shape of the driver's BMW.",
  "bmw-5-series": "Eight generations of the executive saloon.",
  "bmw-7-series": "Seven generations of BMW's technology flagship.",
  "bmw-x1": "The compact SAV, now in its third generation.",
  "bmw-x3": "Four generations of the midsize BMW SAV.",
  "bmw-x5": "The model that started the BMW X family.",
  "bmw-x6": "A coupé roofline and a broad-shouldered stance.",
  "bmw-x7": "BMW's largest three-row SAV.",
  "bmw-m1": "The first standalone icon of BMW Motorsport.",
  "bmw-m2": "Compact proportions. Classic rear-wheel drive.",
  "bmw-m3": "Six generations shaped by motorsport.",
  "bmw-m4": "The two-door performance branch of the 4 Series.",
  "bmw-m5": "Seven generations of the super saloon.",
  "bmw-m6": "Three generations of the flagship M coupé.",
  "bmw-m8": "BMW M in Coupé, Convertible and Gran Coupé form.",
  "bmw-x3-m-f97-lineage": "The first standalone high-performance X3.",
  "bmw-x4-m-f98-lineage": "A BMW M with a Sports Activity Coupé silhouette.",
  "bmw-z3-m": "A compact M roadster and its distinctive coupé sibling.",
  "bmw-z4-m": "A naturally aspirated S54 straight-six in a compact body.",
  "bmw-xm": "The first standalone BMW M since the M1.",
  "bmw-i3-i01-lineage": "BMW i's purpose-built electric city car.",
  "bmw-i4-g26-lineage": "An electric four-door Gran Coupé.",
  "bmw-i5-g60-lineage": "The first electric 5 Series saloon.",
  "bmw-i8": "A hybrid sports car with the spirit of a concept.",
  "bmw-ix1-u11-lineage": "BMW's first electric compact SAV.",
  "bmw-ix2-u10-lineage": "The electric Sports Activity Coupé.",
  "bmw-ix3-g08-lineage": "The first fully electric midsize BMW SAV.",
  "bmw-ix": "BMW's electric technology flagship.",
  "bmw-isetta": "A tiny car. A big chapter in BMW history.",
  "bmw-r32": "The motorcycle that began the BMW Motorrad story.",
  "bmw-gs-boxer": "Five landmarks in the story of the GS boxer.",
  "bmw-s1000rr": "BMW's four-cylinder ShiftCam superbike.",
  "bmw-r18-lineage": "A cruiser built around BMW's big boxer engine.",
  "bmw-ce04-lineage": "An electric scooter with a new view of the city.",
};
